services:
  event-engine:
    build: .
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./k8s:/app/k8s
      - ./kubeconfig.yaml:/app/kubeconfig.yaml
    depends_on:
      - redis
    networks:
      - kind
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - kind
  jaeger: 
    image: jaegertracing/all-in-one:1.55
    ports: 
      - "16686:16686" # Intefaz de Jaeger
      - "6831:6831/udp" # Trazing de opentelemtry
    networks: 
      - kind 
networks:
  kind:
    external: true