services:
  event-engine:
    build: .
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./k8s:/app/k8s
      - ./kubeconfig.yaml:/app/kubeconfig.yaml
    depends_on:
      - redis
    networks:
      - kind
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - kind
networks:
  kind:
    external: true