services:
  event-engine:
    build: .
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    command: pytest tests/ --cov=src --cov-report=term-missing
    depends_on:
      - redis
  redis:
    image: redis:6
    ports:
      - "6379:6379"