#!/bin/bash
MSJ_COMMIT=$1
MENSAJE=$(cat "$MSJ_COMMIT")

# Lista de prefijos estandar
# https://www.conventionalcommits.org/en/v1.0.0/#specification
PATRON="^(feat|fix|refactor|docs|test|chore|style|ci|build|perf|revert|merge|setup)\[#([0-9]+)\]: .+"

if ! echo "$MENSAJE" | grep -Eq "$PATRON"; then
    echo "Error: El mensaje del commit debe seguir el formato '<tipo>[#n]: mensaje'"
    echo "prefijos estandar validos : feat, fix, refactor, docs, test, chore, style, ci, build, perf, revert y merge"
    echo "Ejemplo correcto: fix[#5]: Corregir error en el motor de eventos"
    exit 1
fi

exit 0
